### ISSUE TITLE
add linting

### ISSUE THREAD

**Issue by raoulg** [ThijsVerdouw/Blok-3-exploration#2]
Add a Makefile that lints your code with black, ruff and optional mypy

**Comment by ThijsVerdouw** [comment]
Ik heb mijn code door de linting (black) website heengehaald. De manier waarop mijn comments geschreven zijn word daar niet beter op, het is wat het is. Volgende keer beter.

Voor nu is de echte code in ieder geval goed geformat. Sluit issue.
