### ISSUE TITLE
Organiseer je code

### ISSUE THREAD

**Issue by raoulg** [ThijsVerdouw/Blok-3-exploration#3]
Idealiter gebruik je een cookiecutter. Zie codestyle standards. Organiseer je code op die manier;
een src folder voor je code, een data folder voor je data (nu staat er een  csv file in root)

**Comment by ThijsVerdouw** [comment]
M.B.T. de CSV file in root: dat is een legacy file, ik weet niet hoe ik die kan verwijderen in github. De meest recente csv files staan in data/suffix. Ik ben inderdaad bezig met de code te organiseren.

**Comment by raoulg** [comment]
Gewoon de csv file verwijderen lokaal. Dan git add , git commit en git push. Dan is hij ook hier weg.
Zelfde geldt voor het organiseren van je code; als je niet goed begrijpt hoe git werkt, zie docs/git in de repository

**Comment by ThijsVerdouw** [comment]
Done.
